version: 2

sources:
- database: "{{ var('my_database') }}"
  name: my_source
  schema: "{{ var('my_schema') }}"
  tables:
  - name: fact_revenue
  - name: dim_customer
  - name: dim_product
  - name: dim_entity
  - name: dim_other
  - name: dim_calendar








