name: Incoming PR

run-name: PR opened by ${{ github.actor }}

# on:
#   pull_request:
#     types: [opened, synchronize, reopened, ready_for_review]
#     branches: [main]

on:
  push:
    branches:
      - main

permissions:
  contents: read
  # id-token: write

jobs:
  run-snowflake-test-dbt-job:
    name: Run on Incoming PR
    runs-on: ubuntu-latest

    environment: dbt

    env:
      SNOWFLAKE_CLI_FEATURES_ENABLE_DBT: true
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      
      SNOWFLAKE_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ vars.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v2.0
        # with:
        #   use-oidc: true

      - name: Check Snowflake CLI Version
        run: snow --version

      - name: Test Snowflake Connection
        run: snow connection test -x

      - name: Drop old dbt project
        run: |
          snow sql -q "DROP DBT PROJECT IF EXISTS DBT_SNOWBALL" -x

      - name: Deploy Test dbt Project
        run: |
          snow dbt deploy DBT_SNOWBALL \
          --source ./snowball_dbt-main \
          --dbt-version 1.10.15 \
          --force \
          -x

      # - name: List dbt Projects
      #   run: snow dbt list -x

      # - name: Build and Test dbt Project
      #   run: |
      #     snow dbt execute -x \
      #     DBT_SNOWBALL \
      #     build \
      #     --target dev



      - name: Create Monthly Revenue Task
        run: |
          snow sql -f snowball_dbt-main/monthly_revenue_task.sql -x

      - name: Create Dummy Task
        run: |
          snow sql -f snowball_dbt-main/dummy_task.sql -x

          
   #  Step 7: Suspend parent (required before graph update)
      - name: Suspend Parent Task
        run: |
          snow sql -q "ALTER TASK my_trial_db.cicd_test.monthly_revenue_task SUSPEND" -x



      #  Step 8: Resume Task (important)

      - name: Resume Tasks
        run: |
          snow sql -q "ALTER TASK my_trial_db.cicd_test.monthly_revenue_task RESUME" -x
          snow sql -q "ALTER TASK my_trial_db.cicd_test.dummy_task RESUME" -x


      #  Step 9: Trigger Task (MAIN STEP)
      - name: Trigger Task
        run: |
          snow sql -q "EXECUTE TASK my_trial_db.cicd_test.monthly_revenue_task" -x

      
